export { RightAnswerTaskView } from './right-answer-task-view'
export { AnswerFromSelectView } from './answer-from-select-task-view'
export { CorrectOrderSplitSentenceView } from './correct-order-split-sentence-view'
export { CompareTaskView } from './compare-task-view'
export { CategorizeTaskView } from './categorize-task-view'
